; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nicenano]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
board_build.variants_dir = variants

; --- Build Flags ---
build_flags = 
    -DCFG_SYS_DEBUG=0
    -DARDUINO_NRF52840_FEATHER
    -DCFG_FS_SIZE=65536

; --- Library Dependencies ---
lib_deps =
    GxEPD2 @ 1.6.9
    Adafruit GFX Library @ 1.11.9
    Adafruit BusIO @ 1.16.1
    SPI
    Wire
    greiman/SdFat @ ^2.2.3

; --- Serial Monitor Configurations ---
monitor_speed = 115200
monitor_filters = default, time
